# ============================
# CẤU HÌNH DÀNH CHO MÔI TRƯỜNG DEV
# ============================

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant
    username: postgres
    password: root         # Có thể thay bằng ENV nếu muốn sạch hơn
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none         # Không auto tạo bảng, dùng Flyway 100%
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

jwt:
  secret: restaurant-dev-secret-key-1234567890123456sdadsaqweqweqweqweqwewadsdsfdqwefdggdfsdasdsadwqeqweqwewqeadsasdsadasdasdqweqweqweqwewa
  access-token-expiration-minutes: 60
  refresh-token-expiration-days: 7

momo:

  mode: product

  sandbox:
    endpoint: https://test-payment.momo.vn/v2/gateway/api/create
    partner-code: MOMOTIZB20251112_TEST
    access-key: DOJCAtMxDvslOzlP
    secret-key: TAOGAxV1BEQ5vjUCkrV32IeOMiaBZidX
    redirect-url: http://localhost:5173/payment/momo-return
    ipn-url: http://localhost:8080/api/payments/momo/ipn

  product:
    endpoint: https://payment.momo.vn/v2/gateway/api/create
    partner-code: MOMOTIZB20251112
    access-key: KknmM1RjCrxpDqOj
    secret-key: NdqdNXAJTpwbAQDsQw8hZaZv8SuWu0i2
    redirect-url: http://localhost:5173/payment/momo-return
    ipn-url: http://localhost:8080/api/payments/momo/ipn
